version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: SUB_USER_PASSWORD
      MYSQL_DATABASE: subscriber
      MYSQL_USER: SUB_USER
      MYSQL_PASSWORD: SUB_USER_PASSWORD
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8081:8080"  # Map the Vue.js app to a different port
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
